# name: Django CI

# 動くきっかけ(暫定対応)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 動かす内容
jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest # 実行環境
    steps: # 実行する内容
      - run: echo "Hello World t_kyn!"

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.7, 3.8, 3.9]

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
#     - name: curl Tests
#       run: |
#         curl http://localhost:8080/
