name: LocalStack AWS Infrastructure Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up LocalStack
      run: |
        docker run --rm -d -p 4566:4566 localstack/localstack

    - name: Install AWS CLI
      run: |
        sudo apt-get install -y awscli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id test
        aws configure set aws_secret_access_key test
        aws configure set region us-east-1

    - name: Create VPC
      id: create_vpc
      run: |
        VPC_ID=$(aws --endpoint-url=http://localhost:4566 ec2 create-vpc --cidr-block 10.0.0.0/16 --query "Vpc.VpcId" --output text)
        echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV

    - name: Create Subnets
      run: |
        aws --endpoint-url=http://localhost:4566 ec2 create-subnet --vpc-id ${{ env.VPC_ID }} --cidr-block 10.0.1.0/24 --availability-zone us-east-1a
        aws --endpoint-url=http://localhost:4566 ec2 create-subnet --vpc-id ${{ env.VPC_ID }} --cidr-block 10.0.2.0/24 --availability-zone us-east-1b

    - name: Create Internet Gateway
      run: |
        IGW_ID=$(aws --endpoint-url=http://localhost:4566 ec2 create-internet-gateway --query "InternetGateway.InternetGatewayId" --output text)
        aws --endpoint-url=http://localhost:4566 ec2 attach-internet-gateway --vpc-id ${{ env.VPC_ID }} --internet-gateway-id $IGW_ID

    - name: Create EC2 Instances
      run: |
        PUBLIC_SUBNET_ID=$(aws --endpoint-url=http://localhost:4566 ec2 describe-subnets --query "Subnets[?CidrBlock=='10.0.1.0/24'].SubnetId" --output text)
        PRIVATE_SUBNET_ID=$(aws --endpoint-url=http://localhost:4566 ec2 describe-subnets --query "Subnets[?CidrBlock=='10.0.2.0/24'].SubnetId" --output text)
        
        aws --endpoint-url=http://localhost:4566 ec2 run-instances --image-id ami-12345678 --count 2 --instance-type t2.micro --subnet-id $PUBLIC_SUBNET_ID --associate-public-ip-address
        aws --endpoint-url=http://localhost:4566 ec2 run-instances --image-id ami-12345678 --count 2 --instance-type t2.micro --subnet-id $PRIVATE_SUBNET_ID

    - name: Create S3 Bucket
      run: |
        aws --endpoint-url=http://localhost:4566 s3 mb s3://my-test-bucket

    - name: Create API Gateway
      run: |
        API_ID=$(aws --endpoint-url=http://localhost:4566 apigateway create-rest-api --name "my-api" --query "id" --output text)
        echo "API_ID=$API_ID" >> $GITHUB_ENV

    - name: Create Lambda Function
      run: |
        ZIP_FILE="function.zip"
        echo "exports.handler = async (event) => { return { statusCode: 200, body: 'Hello from Lambda!' }; };" > index.js
        zip $ZIP_FILE index.js
        LAMBDA_ROLE_ARN=$(aws --endpoint-url=http://localhost:4566 iam create-role --role-name lambda-role --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}' --query "Role.Arn" --output text)
        aws --endpoint-url=http://localhost:4566 iam attach-role-policy --role-name lambda-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        aws --endpoint-url=http://localhost:4566 lambda create-function --function-name my-function --runtime nodejs14.x --role $LAMBDA_ROLE_ARN --handler index.handler --zip-file fileb://$ZIP_FILE

    # - name: Create Aurora Database Cluster
    #   run: |
    #     CLUSTER_ID=$(aws --endpoint-url=http://localhost:4566 rds create-db-cluster --db-cluster-identifier my-cluster --engine aurora --master-username master --master-user-password password --query "DBCluster.DBClusterIdentifier" --output text)
    #     aws --endpoint-url=http://localhost:4566 rds create-db-instance --db-instance-identifier my-cluster-instance --db-instance-class db.t3.medium --engine aurora --db-cluster-identifier $CLUSTER_ID
    #     aws --endpoint-url=http://localhost:4566 rds create-db-instance --db-instance-identifier my-cluster-instance-replica --db-instance-class db.t3.medium --engine aurora --db-cluster-identifier $CLUSTER_ID --db-instance-role reader

    - name: Create DynamoDB Table
      run: |
        aws --endpoint-url=http://localhost:4566 dynamodb create-table \
          --table-name my-table \
          --attribute-definitions AttributeName=id,AttributeType=N \
          --key-schema AttributeName=id,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

    # - name: Create RDS Oracle Instances
    #   run: |
    #     # Create master DB instance
    #     MASTER_DB_ID=$(aws --endpoint-url=http://localhost:4566 rds create-db-instance \
    #       --db-instance-identifier my-oracle-master \
    #       --db-instance-class db.t3.micro \
    #       --engine oracle-se2 \
    #       --allocated-storage 20 \
    #       --master-username admin \
    #       --master-user-password password \
    #       --db-name mydatabase \
    #       --query "DBInstance.DBInstanceIdentifier" --output text)
        
    #     # Create read replica of master DB instance
    #     aws --endpoint-url=http://localhost:4566 rds create-db-instance \
    #       --db-instance-identifier my-oracle-replica \
    #       --db-instance-class db.t3.micro \
    #       --engine oracle-se2 \
    #       --source-db-instance-identifier $MASTER_DB_ID \
    #       --allocated-storage 20


    - name: Install Python and Diagrams
      run: |
        sudo apt-get install -y python3 python3-pip
        pip3 install diagrams

#     - name: Generate Architecture Diagram
#       run: |
#         # Create a Python script file
#         cat > generate_diagram.py <<EOF
# from diagrams import Diagram, Cluster
# from diagrams.aws.network import VPC, PublicSubnet, PrivateSubnet, InternetGateway
# from diagrams.aws.compute import EC2
# from diagrams.aws.storage import S3
# from diagrams.aws.network import APIGateway
# from diagrams.aws.compute import Lambda
# from diagrams.aws.database import RDS

# with Diagram("AWS Infrastructure", show=False):
#     vpc = VPC("VPC")
    
#     with Cluster("Public Subnet"):
#         public_subnet = PublicSubnet("Public Subnet")
#         ec2_public_1 = EC2("EC2 Instance (Public)")
#         ec2_public_2 = EC2("EC2 Instance (Public)")
#         public_subnet >> ec2_public_1
#         public_subnet >> ec2_public_2

#     with Cluster("Private Subnet"):
#         private_subnet = PrivateSubnet("Private Subnet")
#         ec2_private_1 = EC2("EC2 Instance (Private)")
#         ec2_private_2 = EC2("EC2 Instance (Private)")
#         private_subnet >> ec2_private_1
#         private_subnet >> ec2_private_2

#     igw = InternetGateway("Internet Gateway")
#     vpc >> igw

#     s3 = S3("S3 Bucket")
#     api_gateway = APIGateway("API Gateway")
#     lambda_func = Lambda("Lambda Function")

#     rds = RDS("Aurora Cluster")
#     master_db = RDS("Master Instance")
#     replica_db = RDS("Read Replica")

#     s3
#     api_gateway
#     lambda_func
#     rds >> master_db
#     rds >> replica_db
# EOF

#         # Run the Python script to generate the diagram
#         python3 generate_diagram.py

#         # Rename the output diagram if needed
#         mv architecture.png architecture-diagram.png


    # - name: Upload Diagram
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: architecture-diagram
    #     path: architecture.png
  dust_resources_delete:
    runs-on: ubuntu-latest

    steps:
    - name: Set up LocalStack
      uses: localstack/github-action@v1
      with:
        services: ec2, s3, apigateway, lambda
        debug: true

    - name: Delete EC2 Instances
      run: |
        INSTANCE_IDS=$(aws --endpoint-url=http://localhost:4566 ec2 describe-instances --query "Reservations[*].Instances[*].InstanceId" --output text)
        for instance_id in $INSTANCE_IDS; do
          aws --endpoint-url=http://localhost:4566 ec2 terminate-instances --instance-ids $instance_id
        done
        aws --endpoint-url=http://localhost:4566 ec2 wait instance-terminated --instance-ids $INSTANCE_IDS

    - name: Delete VPCs
      run: |
        VPC_IDS=$(aws --endpoint-url=http://localhost:4566 ec2 describe-vpcs --query "Vpcs[*].VpcId" --output text)
        for vpc_id in $VPC_IDS; do
          IGW_ID=$(aws --endpoint-url=http://localhost:4566 ec2 describe-internet-gateways --filters Name=attachment.vpc-id,Values=$vpc_id --query "InternetGateways[0].InternetGatewayId" --output text)
          if [ "$IGW_ID" != "None" ]; then
            aws --endpoint-url=http://localhost:4566 ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $vpc_id
            aws --endpoint-url=http://localhost:4566 ec2 delete-internet-gateway --internet-gateway-id $IGW_ID
          fi
          SUBNET_IDS=$(aws --endpoint-url=http://localhost:4566 ec2 describe-subnets --filters Name=vpc-id,Values=$vpc_id --query "Subnets[*].SubnetId" --output text)
          for subnet_id in $SUBNET_IDS; do
            aws --endpoint-url=http://localhost:4566 ec2 delete-subnet --subnet-id $subnet_id
          done
          aws --endpoint-url=http://localhost:4566 ec2 delete-vpc --vpc-id $vpc_id
        done

    - name: Delete S3 Buckets
      run: |
        BUCKETS=$(aws --endpoint-url=http://localhost:4566 s3api list-buckets --query "Buckets[*].Name" --output text)
        for bucket in $BUCKETS; do
          aws --endpoint-url=http://localhost:4566 s3 rb s3://$bucket --force
        done

  terraform_apply:
    runs-on: ubuntu-latest
    needs: [localstack_test, dust_resources_delete]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Apply Terraform configuration
      run: |
        cd terraform
        terraform apply -auto-approve