name: TFLocal Workflow

on: [push]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  terraform-local:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12  # 互換性のある Docker バージョンを指定
        options: --privileged    # Docker コンテナ内で Docker を実行するためのオプション

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # # LocalStack のセットアップ
    # - name: Set up LocalStack
    #   uses: localstack/localstack-action@v1
    #   with:
    #     services: ec2, s3, apigateway, lambda

    # - name: Set up LocalStack
    #   run: |
    #     docker run --rm -d -p 4566:4566 localstack/localstack
    # - name: Set up LocalStack
      # run: |
      #   docker run --rm -d -p 4566:4566 -p 4571:4571 localstack/localstack -e LAMBDA_EXECUTOR=docker
      #   sleep 10  # コンテナ起動待機
    - name: Set up LocalStack
      run: |
        docker run --rm -d -p 4566:4566 -p 4571:4571 \
          -e LAMBDA_EXECUTOR=docker \
          -e SERVICES=lambda,ec2,vpc,s3,apigateway,iam \
          -e DEBUG=1 \
          -e LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse} \
          -e DOCKER_HOST=unix:///var/run/docker.sock \
          localstack/localstack

    # - name: Wait for LocalStack to be ready
    #   run: |
    #     until curl -s http://localhost:4566/_localstack/health | grep '"services": {"lambda": "running"}'; do
    #       echo "Waiting for LocalStack..."
    #       sleep 5
    #     done

    - name: Check Docker availability
      run: |
        docker --version

    # # TFLocal のインストール
    # - name: Install TFLocal
    #   run: |
    #     pip install localstack-client
    #     wget https://github.com/localstack/terraform-local/releases/download/v0.13/tflocal-linux-amd64
    #     chmod +x tflocal-linux-amd64
    #     sudo mv tflocal-linux-amd64 /usr/local/bin/tflocal
    # TFLocal のインストール
    - name: Install TFLocal
      run: |
          pip install localstack-client
          pip install terraform-local
    #       git clone https://github.com/localstack/terraform-local.git
    #       ls -lrtR
    #       chmod -x terraform-local/bin/tflocal
    #       sudo mv terraform-local/bin/tflocal terraform/tflocal
    # chmod +x tflocal-linux-amd64
    # sudo mv tflocal-linux-amd64 /usr/local/bin/tflocal

    # 暫定追加
    - name: Print current directory(Temporary add 2024/09/07)
      run: ls -lrt

    # Lambdaのファイルがあるかの事前確認
    - name: Verify ZIP file creation
      run: |
        cd terraform
        ls -la lambda/
        unzip -l lambda/lambda_function_payload.zip

    # Terraform の初期化
    - name: Initialize TFLocal
      run: |
        cd terraform
        tflocal init

    # Terraform の適用
    - name: Apply TFLocal configuration
      run: |
        cd terraform
        ls -lrtR
        tflocal apply -auto-approve

    # 出力の確認
    - name: Output TFLocal state
      run: |
        cd terraform
        tflocal output