name: TFLocal Workflow

on: [push]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  terraform-local:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # # LocalStack のセットアップ
    # - name: Set up LocalStack
    #   uses: localstack/localstack-action@v1
    #   with:
    #     services: ec2, s3, apigateway, lambda

    - name: Set up LocalStack
      run: |
        docker run --rm -d -p 4566:4566 localstack/localstack

    # # TFLocal のインストール
    # - name: Install TFLocal
    #   run: |
    #     pip install localstack-client
    #     wget https://github.com/localstack/terraform-local/releases/download/v0.13/tflocal-linux-amd64
    #     chmod +x tflocal-linux-amd64
    #     sudo mv tflocal-linux-amd64 /usr/local/bin/tflocal
    # TFLocal のインストール
    - name: Install TFLocal
      run: |
          pip install localstack-client
          pip install terraform-local
    #       git clone https://github.com/localstack/terraform-local.git
    #       ls -lrtR
    #       chmod -x terraform-local/bin/tflocal
    #       sudo mv terraform-local/bin/tflocal terraform/tflocal
    # chmod +x tflocal-linux-amd64
    # sudo mv tflocal-linux-amd64 /usr/local/bin/tflocal

    # 暫定追加
    - name: Print current directory(Temporary add 2024/09/07)
      run: ls -lrt
    # Terraform の初期化
    - name: Initialize TFLocal
      run: |
        cd terraform
        tflocal init

    # Terraform の適用
    - name: Apply TFLocal configuration
      run: |
        cd terraform
        ls -lrt
        tflocal apply -auto-approve

    # 出力の確認
    - name: Output TFLocal state
      run: |
        cd terraform
        tflocal output